workflows:
  echo_apk_build:
    name: Echo APK Build
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    scripts:
      - name: Install Dependencies
        script: |
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
